baseurl = "/"
languageCode = "en-us"
title = "Pavitra Logeswaran"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Pavitra Logeswaran"
	description = "Pavitra Logeswaran is a Toronto-based multidisciplinary designer specializing in user experience and visual design."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "I'm **Pavi**, a **Toronto-based designer**<br> specializing in **user experience**<br> and **visual design**."
		# The icons will be shown if you enter your username
		twitter = "pavi_design"
		github = ""
		dribbble = "Pavitra"
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "pavitra-logeswaran-78637187"

		copyright = [
			"&copy; Pavitra Logeswaran 2018"
		]


	[params.about]
		hide  = true
		title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


	[params.portfolio]
		hide  = false
		title = ""

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			# thumb = "thumbs/01.jpg"
			thumb = "portfolio/tempo/tempo-intro.png"
			title = ""
			description = ""

		# [[params.portfolio.gallery]]
		# 	image = "fulls/02.jpg"
		# 	thumb = "thumbs/02.jpg"
		# 	title = "Lorem ipsum dolor."
		# 	description = "Lorem ipsum dolor sit amet."

		# [[params.portfolio.gallery]]
		# 	image = "fulls/03.jpg"
		# 	thumb = "thumbs/03.jpg"
		# 	title = "Lorem ipsum dolor."
		# 	description = "Lorem ipsum dolor sit amet."

		# [[params.portfolio.gallery]]
		# 	image = "fulls/04.jpg"
		# 	thumb = "thumbs/04.jpg"
		# 	title = "Lorem ipsum dolor."
		# 	description = "Lorem ipsum dolor sit amet."

		# [[params.portfolio.gallery]]
		# 	image = "fulls/05.jpg"
		# 	thumb = "thumbs/05.jpg"
		# 	title = "Lorem ipsum dolor."
		# 	description = "Lorem ipsum dolor sit amet."

		# [[params.portfolio.gallery]]
		# 	image = "fulls/06.jpg"
		# 	thumb = "thumbs/06.jpg"
		# 	title = "Lorem ipsum dolor."
		# 	description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = " "

		address = [
			"Toronto, Ontario"
		]
		phone = "416-509-7294"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "pavilogeswa@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
# [[menu.main]]
# 	name = "Home"
# 	url  = "/"
# 	weight = 1

[[menu.main]]
	name = "Portfolio"
	url  = "https://pavi.design/#portfolio-section"
	jump = false
	weight = 1

[[menu.main]]
    name = "Blog"
    url  = "https://medium.com/@pavilogeswa"
    jump = true
    weight = 2

[[menu.main]]
    name = "Visual"
    url  = "/visual/overview"
    jump = false
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "https://pavi.design/#contact-form"
    jump = false
    weight = 4

# [[menu.main]]
# 	name = "Contact"
# 	url  = "post/"
# 	weight = 2

# [[menu.main]]
# 	name = "About"
# 	url  = "about"
# 	weight = 3
